### ISSUE TITLE
Annoucement Model Validation Error

### ISSUE THREAD

**Issue by seriaati** [seriaati/genshin.py#107]
If no `lang` is provided to the  `get_genshin_annoucements()` method, the following exception is raised.
The client being used here has a Cookie.  

Traceback:
```py
Traceback (most recent call last):
  File "<repl>", line 2, in _repl_coroutine
    await _bot.genshin_client.get_genshin_announcements()
  File "/home/seria/.local/lib/python3.10/site-packages/genshin/client/components/hoyolab.py", line 108, in get_genshin_announcements
    return [models.Announcement(**i) for i in announcements]
  File "/home/seria/.local/lib/python3.10/site-packages/genshin/client/components/hoyolab.py", line 108, in <listcomp>
    return [models.Announcement(**i) for i in announcements]
  File "/home/seria/.local/lib/python3.10/site-packages/genshin/models/model.py", line 78, in __init__
    super().__init__(**data, lang=lang)
pydantic.error_wrappers.ValidationError: 1 validation error for Announcement
tag_label
  value is not a valid integer (type=type_error.integer)
  ```

**Comment by ashleney** [comment]
Cannot reproduce, might have been a temporary issue due to an update 🤔

**Comment by ashleney** [comment]
oh it just happens randomly
