### ISSUE TITLE
Can't get genshin data

### ISSUE THREAD

**Issue by yaser01** [seriaati/genshin.py#109]
OS: Ubuntu 20.04.5 LTS aarch64
Python: 3.8.10
Genshin Library : 1.5.1
Here is the python script:

```
import asyncio
import genshin

async def main():
    cookies = {"ltuid": 119480035, "ltoken": "cnF7TiZqHAAvYqgCBoSPx5EjwezOh1ZHoqSHf7dT"}
    client = genshin.Client(cookies)
    data = await client.get_genshin_user(710785423)
    print(f"User has a total of {data.stats.characters} characters")

asyncio.run(main())
```
Here is the Exception traceback:
```

Traceback (most recent call last):
  File "test2.py", line 10, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "test2.py", line 7, in main
    data = await client.get_genshin_user(710785423)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/genshin/client/components/chronicle/genshin.py", line 95, in get_genshin_user
    return models.GenshinUserStats(**data)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/genshin/models/model.py", line 78, in __init__
    super().__init__(**data, lang=lang)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pydantic/main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pydantic/main.py", line 1076, in validate_model
    v_, errors_ = field.validate(value, values, loc=field.alias, cls=cls_)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pydantic/fields.py", line 895, in validate
    v, errors = self._validate_sequence_like(v, values, loc, cls)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pydantic/fields.py", line 928, in _validate_sequence_like
    r, ee = self._validate_singleton(v_, values, v_loc, cls)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pydantic/fields.py", line 1094, in _validate_singleton
    value, error = field.validate(v, values, loc=loc, cls=cls)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pydantic/fields.py", line 884, in validate
    v, errors = self._validate_singleton(v, values, loc, cls)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pydantic/fields.py", line 1101, in _validate_singleton
    return self._apply_validators(v, values, loc, cls, self.validators)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pydantic/fields.py", line 1151, in _apply_validators
    v = validator(cls, v, values, self, self.model_config)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pydantic/class_validators.py", line 337, in <lambda>
    return lambda cls, v, values, field, config: validator(v)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pydantic/main.py", line 711, in validate
    return cls(**value)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/genshin/models/model.py", line 78, in __init__
    super().__init__(**data, lang=lang)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pydantic/main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pydantic/main.py", line 1050, in validate_model
    input_data = validator(cls_, input_data)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/genshin/models/genshin/character.py", line 111, in __autocomplete
    char = _get_db_char(id, name, icon, element, rarity, lang=values["lang"])
  File "/home/ubuntu/.local/lib/python3.8/site-packages/genshin/models/genshin/character.py", line 55, in _get_db_char
    raise Exception(
Exception: Character names not loaded for None. Please run `await genshin.utility.update_characters_any()`.
```

I have tried to run the above function but with no help nothing changed !

**Comment by ashleney** [comment]
That's odd, I thought that this should be done automatically for this use case.

It's telling you to run it like this for a temporary fix:
```py
import asyncio
import genshin

async def main():
    cookies = {"ltuid": 119480035, "ltoken": "cnF7TiZqHAAvYqgCBoSPx5EjwezOh1ZHoqSHf7dT"}
    client = genshin.Client(cookies)
    await genshin.utility.update_characters_any()
    data = await client.get_genshin_user(710785423)
    print(f"User has a total of {data.stats.characters} characters")

asyncio.run(main())
````

**Comment by yaser01** [comment]
> That's odd, I thought that this should be done automatically for this use case.
> 
> It's telling you to run it like this for a temporary fix:
> 
> ```python
> import asyncio
> import genshin
> 
> async def main():
>     cookies = {"ltuid": 119480035, "ltoken": "cnF7TiZqHAAvYqgCBoSPx5EjwezOh1ZHoqSHf7dT"}
>     client = genshin.Client(cookies)
>     await genshin.utility.update_characters_any()
>     data = await client.get_genshin_user(710785423)
>     print(f"User has a total of {data.stats.characters} characters")
> 
> asyncio.run(main())
> ```

Same Exception Same Line
```
 File "test2.py", line 8, in main
    data = await client.get_genshin_user(710785423) .....
```
I am running this on Linux Arm64 on oracle instant 
The same code run very well on my laptop Windows 10 amd64
If there anything i can help to debug this tell me

**Comment by ashleney** [comment]
I tried to run this on an ubuntu code server but it worked fine. What I believe is happening is that pydantic is not properly passing through the `lang` field. What's your version of pydantic? It works on 1.10.x on my machine. Could it be that maybe pydantic stopped supporting some infrastructure?

**Comment by yaser01** [comment]
pydantic version is 1.10.7 
what should i try to test it?

**Comment by ashleney** [comment]
I have diagnosed the error. Pydantic was installed uncompiled and for some reason has different behavior. 
Specifically, compiled frames are not exposed by default, while uncompiled frames are. This prevents the library from searching for the `lang` field in the parent models.

To immediately fix the issue you can try to install compiled pydantic: https://docs.pydantic.dev/install/#compiled-with-cython

I will try to find a fix that will support both compiled and uncompiled versions.

**Comment by yaser01** [comment]
Thanks bro :D
Problem Solved 
I have just re-install pydantic with this command:
```
CFLAGS="-Os -g0 -s" pip install \
  --no-binary pydantic \
  --global-option=build_ext \
  pydantic
```
