### ISSUE TITLE
Daily reward for ZZZ not working

### ISSUE THREAD

**Issue by sanioooook** [seriaati/genshin.py#227]
Yesterday everything worked fine, but today I get this error

```
Traceback (most recent call last):
  File "./main.py", line 50, in <module>
    asyncio.run(main())
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "./main.py", line 15, in main
    await client.claim_daily_reward(reward=False)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/genshin/client/components/daily.py", line 172, in claim_daily_reward
    await self.request_daily_reward("sign", method="POST", game=game, lang=lang, challenge=challenge)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/genshin/client/components/daily.py", line 82, in request_daily_reward
    return await self.request(url, method=method, params=params, headers=headers, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/genshin/client/components/base.py", line 377, in request
    response = await self.cookie_manager.request(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/genshin/client/manager/managers.py", line 283, in request
    return await self._request(method, url, cookies=self.cookies, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/genshin/client/ratelimit.py", line 25, in inner
    x = await func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/genshin/client/manager/managers.py", line 174, in _request
    errors.raise_for_retcode(data)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/genshin/errors.py", line 337, in raise_for_retcode
    raise GenshinException(data)
genshin.errors.GenshinException: [-500012] 活动已结束 (-500012)
``` 

the code was run daily, the code is the simplest like
```python
for game in [genshin.Game.GENSHIN, genshin.Game.ZZZ]:
    client = genshin.Client(cookies={"ltuid":ltuidEnv, "ltoken":ltokenEnv}, lang=langEnv, game=game)
    client.claim_daily_reward(reward=False)
```

**Comment by kgirtxd** [comment]
Update to python 3.9+ (3.8 is not longer supported by this repo but may work) and update to the latest version of the master branch.  Let us know if that fixes it

**Comment by sanioooook** [comment]
yes, it helped for github, but locally I get the same error (Python 3.11.4 and genshin 1.7.1 are installed locally)

**Comment by kgirtxd** [comment]
run the below to make sure you have the absolute latest version
pip install git+https://github.com/thesadru/genshin.py --force-reinstall -U

**Comment by sanioooook** [comment]
it helped, thank you very much
