### ISSUE TITLE
InternalDatabaseError when trying to get genshin characters (Nilou's id doesn't exist)

### ISSUE THREAD

**Issue by ElReyZero** [seriaati/genshin.py#70]
Obtaining this exception when trying to retrieve the genshin characters from the API. It's due to Nilou's ID not being in the internal database.

```
Traceback (most recent call last):
  File "C:\Users\ElRey\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\tasks\__init__.py", line 239, in _loop
    await self.coro(*args, **kwargs)
  File "c:\Users\ElRey\Documents\Scripts\Python\ReyBot\discord_tools\tasks.py", line 10, in updateGenshinChars    
    chars = await client.get_genshin_characters(cfg.genshin_data["uuid"])
  File "C:\Users\ElRey\AppData\Local\Programs\Python\Python310\lib\site-packages\genshin\client\components\chronicle\genshin.py", line 78, in get_genshin_characters
    data = await self._request_genshin_record("character", uid, lang=lang, method="POST")
  File "C:\Users\ElRey\AppData\Local\Programs\Python\Python310\lib\site-packages\genshin\client\components\chronicle\genshin.py", line 51, in _request_genshin_record
    return await self.request_game_record(
  File "C:\Users\ElRey\AppData\Local\Programs\Python\Python310\lib\site-packages\genshin\client\components\chronicle\base.py", line 63, in request_game_record
    data = await self.request_hoyolab(url, lang=lang, region=region, **kwargs)
  File "C:\Users\ElRey\AppData\Local\Programs\Python\Python310\lib\site-packages\genshin\client\components\base.py", line 380, in request_hoyolab
    data = await self.request(url, method=method, params=params, data=data, headers=headers, **kwargs)
  File "C:\Users\ElRey\AppData\Local\Programs\Python\Python310\lib\site-packages\genshin\client\components\base.py", line 294, in request
    response = await self.cookie_manager.request(
  File "C:\Users\ElRey\AppData\Local\Programs\Python\Python310\lib\site-packages\genshin\client\manager.py", line 243, in request
    return await self._request(method, url, cookies=self.cookies, **kwargs)
  File "C:\Users\ElRey\AppData\Local\Programs\Python\Python310\lib\site-packages\genshin\client\ratelimit.py", line 24, in inner
    x = await func(*args, **kwargs)
  File "C:\Users\ElRey\AppData\Local\Programs\Python\Python310\lib\site-packages\genshin\client\manager.py", line 137, in _request
    errors.raise_for_retcode(data)
  File "C:\Users\ElRey\AppData\Local\Programs\Python\Python310\lib\site-packages\genshin\errors.py", line 224, in raise_for_retcode
    raise exctype(data, msg)
genshin.errors.InternalDatabaseError: [-1] character id:10000070 is not exists
```

**Comment by GauravM512** [comment]
That's hoyolab issue afaik

**Comment by ElReyZero** [comment]
You sure? I can access my battle chronicle on Hoyolab and see Nilou without any issues. Maybe it's an issue with their API if that were the case

**Comment by ashleney** [comment]
It appears that hoyo solved the issue on their side. The genshin function now works fine for users with Nirou.

**Comment by ElReyZero** [comment]
Looks like it's solved yeah
