### ISSUE TITLE
LookupError: unknown encoding: locale

### ISSUE THREAD

**Issue by Hiro420** [seriaati/genshin.py#97]
Traceback (most recent call last):
  File "c:\Users\nikur\Documents\CheckIn.py", line 2, in <module>
    import genshin
  File "C:\Users\nikur\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\genshin\__init__.py", line 7, in <module>
    from . import models, utility
  File "C:\Users\nikur\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\genshin\utility\__init__.py", line 2, in <module>
    from . import geetest
  File "C:\Users\nikur\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\genshin\utility\geetest.py", line 6, in <module>
    import aiohttp
  File "C:\Users\nikur\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\aiohttp\__init__.py", line 6, in <module>
    from .client import (
  File "C:\Users\nikur\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\aiohttp\client.py", line 36, in <module>
    from . import hdrs, http, payload
  File "C:\Users\nikur\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\aiohttp\http.py", line 7, in <module>
    from .http_parser import (
  File "C:\Users\nikur\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\aiohttp\http_parser.py", line 29, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "C:\Users\nikur\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\aiohttp\helpers.py", line 58, in <module>
    IS_MACOS = platform.system() == "Darwin"
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\platform.py", line 921, in system
    return uname().system
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\platform.py", line 856, in uname
    release, version, csd, ptype = win32_ver()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\platform.py", line 368, in win32_ver
    major, minor, build = map(int, _syscmd_ver()[2].split('.'))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\platform.py", line 282, in _syscmd_ver
    info = subprocess.check_output(cmd,
  File "c:\Users\nikur\Documents\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "c:\Users\nikur\Documents\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\Users\nikur\Documents\subprocess.py", line 963, in __init__
    self.stdout = io.TextIOWrapper(self.stdout,
LookupError: unknown encoding: local

**Comment by ashleney** [comment]
This is an issue with the aiohttp library. Make sure it's up to date and if the error persists please open an issue there.
